---
apiVersion: v1
data:
  app.ini: |
    APP_NAME = Gogs on k8s
    RUN_USER = git
    RUN_MODE = prod

    [database]
    DB_TYPE  = sqlite3
    HOST     = 127.0.0.1:3306
    NAME     = gogs
    USER     = root
    PASSWD   =
    SSL_MODE = disable
    PATH     = data/gogs.db

    [repository]
    ROOT = /data/git/gogs-repositories

    [server]
    ROOT_URL         = http://gogs.k8s/
    DOMAIN           = gogs.k8s
    HTTP_PORT        = 3000
    SSH_PORT         = 22

    [mailer]
    ENABLED = false

    [service]
    REGISTER_EMAIL_CONFIRM = false
    ENABLE_NOTIFY_MAIL     = false
    DISABLE_REGISTRATION   = false
    ENABLE_CAPTCHA         = false
    REQUIRE_SIGNIN_VIEW    = false

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = false

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Trace
    ROOT_PATH = /app/gogs/log

    [security]
    INSTALL_LOCK = true
    SECRET_KEY   = idiLVJPW0MdFYOi
kind: ConfigMap
metadata:
  labels:
    app: gogs
  name: gogs-main-config
  namespace: default
